# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mrepo < Formula
  desc ""
  homepage "https://github.com/RaaLabs/mrepo"
  version "0.0.1-rc2"

  on_macos do
    url "https://github.com/RaaLabs/mrepo/releases/download/v0.0.1-rc2/mrepo_0.0.1-rc2_darwin_all.tar.gz"
    sha256 "a2713f732e74d199fda1f6d20cbeea75125a35cb4cb81bfa5dde14ae2ea423cb"

    def install
      bin.install "mrepo"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/RaaLabs/mrepo/releases/download/v0.0.1-rc2/mrepo_0.0.1-rc2_linux_arm64.tar.gz"
      sha256 "17258bbace5de0e8f106cb521207d8352ea3771b5b0a13159cabe19a5c188f34"

      def install
        bin.install "mrepo"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/RaaLabs/mrepo/releases/download/v0.0.1-rc2/mrepo_0.0.1-rc2_linux_amd64.tar.gz"
      sha256 "ef71ea8b817d5f6e566780c0cdabbc586221507b7565e8598fa7d681551f33cc"

      def install
        bin.install "mrepo"
      end
    end
  end
end
